apiVersion: v1
kind: Service
metadata:
  labels:
    stack: {{ .Release.Name }}
    app: redis
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    stack: {{ .Release.Name }}
  type: ClusterIP