apiVersion: v1
kind: Service
metadata:
  labels:
    stack: {{ .Release.Name }}
    app: rng
  name: rng
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    stack: {{ .Release.Name }}
    app: rng
  type: ClusterIP